### ISSUE TITLE
[1.16.5 BUG] Quark kick Packet processing error

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1559] opened 2021-07-13 23:46 UTC
i use last version mohist..

1.16.5 Minecraft

Mods: Quark

i equip backpack and craft in crafting table in inventory and me kick :D fix pls..

https://paste.ubuntu.com/p/SD3CyFY3Hs/

**Comment by Shawiizz** [comment] 2021-07-15 14:58
Duplicate of #1554

**Closed as completed by Shawiizz** 2021-07-15 14:58 UTC
