### ISSUE TITLE
[1.20.1] Issues with ConnectorExtras

### ISSUE THREAD

**Issue by GeekCornerGH** [Teneted/Tenet#3014] opened 2024-03-21 08:48 UTC
**Minecraft Version :** 1.20.1

**Mohist Version :** 627

**Operating System :** Ubuntu 22.04 Jamy (through Docker image ghcr.io/pterodactyl/yolks:java_17)

**Concerned mod / plugin** : https://modrinth.com/mod/creativecore/version/2.11.25

**Logs :** With [CreativeCore](https://gist.github.com/GeekCornerGH/09e2a28cd6713513d72d3ebab7e25776#file-with-creative-core-log) [Without CreativeCore](https://gist.github.com/GeekCornerGH/09e2a28cd6713513d72d3ebab7e25776#file-without-creative-core-log)
**Steps to Reproduce :**
 1. Add LittleTiles, and CreativeCore
 2. Boot up a MohistMC 1.20.1 with the build 627
 3. ???
 4. See the logs (no crash report will be produced)
 5. Remove CreativeCore
 6. Reboot the server
 7. ???
 8. A proper crash report will be generated, but server won't boot without CreativeCore
 9. Enjoy

**Description of issue :** The exacte same modlist will boot properly on regular Forge (47.2.20)

**Comment by Mgazul** [comment] 2024-03-21 09:28
The problem is caused by reach-entity-attributes mod

**Comment by GeekCornerGH** [comment] 2024-03-21 10:01
> The problem is caused by reach-entity-attributes mod

@Mgazul thanks for the fast reply. The issue seems produced by [ConnectorExtras](https://modrinth.com/mod/connector-extras) (which indeed uses reach-entity-attributes library). We use it because we use Architectury too.
After removing the mod, it seems it will boot up properly. Is it planned to fix that behaviour?

**Comment by GeekCornerGH** [comment] 2024-03-21 14:27
@TonimatasDEV you said in #2842 that you would fix any mixins issues with fabric, would you consider fixing this maybe?

**Comment by TonimatasDEV** [comment] 2024-03-21 14:44
> @TonimatasDEV you said in #2842 that you would fix any mixins issues with fabric, would you consider fixing this maybe?

I need to see it

**Comment by GeekCornerGH** [comment] 2024-03-21 14:55
> I need to see it

The stacktrace? [Here is it](https://gist.github.com/GeekCornerGH/09e2a28cd6713513d72d3ebab7e25776#file-with-creative-core-log-L74-L149)

**Comment by Mgazul** [comment] 2024-03-22 06:31
```@Shadow field f_143670_ was not located in the target class net.minecraft.server.network.ServerGamePacketListenerImpl$1```
net.minecraft.server.network.ServerGamePacketListenerImpl$1 and f_143670_ do not exist in forge. This is probably something unique to fabric.

**Comment by TonimatasDEV** [comment] 2024-03-22 14:57
> `@Shadow field f_143670_ was not located in the target class net.minecraft.server.network.ServerGamePacketListenerImpl$1` net.minecraft.server.network.ServerGamePacketListenerImpl$1 and f_143670_ do not exist in forge. This is probably something unique to fabric.

In normal forge works

**Comment by GeekCornerGH** [comment] 2024-03-22 16:59
Indeed, it is an incompatibility with Mohist, hence why I opened the issue here. By the way, I'm available for testing, just tag me in a PR :)

**Comment by Magi1053** [comment] 2024-04-17 03:36
Still having this issue on the latest version. Not being able to use Connector Extras is a major inconvenience, is this planned to be fixed in the near future?

**Comment by TrickShow** [comment] 2024-04-23 03:43
I am also running into this issue and it's a huge pain not being able to use Connector Extras. Is there any eta on if or when this will be fixed?

**Comment by Magi1053** [comment] 2024-05-23 01:43
At this point am I suppose to give up hope that this will ever be fixed.

**Comment by Mgazul** [comment] 2024-06-18 16:28
Fixed

**Closed as completed by Mgazul** 2024-06-18 16:28 UTC

**Comment by Explode007** [comment] 2024-09-04 03:07
Valkyrien skies breaks whatever was fixed here. I don't know what mohist is, I just found this thread and this seems relevant

[https://pastebin.com/c5Qaic7K](url)
