### ISSUE TITLE
[BUG 1.16.5] There are too many thunderstorms and rains. 

### ISSUE THREAD

**Issue by MrJorman** [Teneted/Tenet#1523] opened 2021-07-09 11:18 UTC
**Minecraft Version:** 1.16.5

**Mohist Version:** build#698

**Operating System:** Windows 10 64 Bits

**Logs:** NONE

**Mod list:** NONE

**Plugin list:** NONE

**Description of issue:** There are too many thunderstorms and rains.

**Comment by Shawiizz** [comment] 2021-07-09 14:38
Cannot reproduce. I think you just don't know how rain is in normal Minecraft.
I close this for now, if someone can reproduce, tell me.

**Closed as completed by Shawiizz** 2021-07-09 14:38 UTC
Labels: 1.16.5, Cannot Reproduce
