### ISSUE TITLE
[1.16.5] Kiwi is not working

### ISSUE THREAD

**Issue by jellybean13** [Teneted/Tenet#1426] opened 2021-06-10 10:38 UTC
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-632

**Operating System :** Linux Ubuntu 21.04

**Concerned mod / plugin** : [Kiwi](https://www.curseforge.com/minecraft/mc-mods/kiwi)

**Logs :** https://paste.ubuntu.com/p/WNYDX4vq9Z

**Steps to Reproduce :**
 1. Start the server with "Snow! Real Magic! " and its dependency (Kiwi).
 2. Wait a minute, the server will crash.

**Description of issue :** Kiwi 3.5.1 can work on Mohist 1.16.5-621. However, it can not working on Mohist 1.16.5-632, which causes the server crash.

**Comment by Shawiizz** [comment] 2021-06-10 10:39
Duplicate of #1425

**Closed as completed by Shawiizz** 2021-06-10 10:39 UTC
Labels: Bug, Duplicate, 1.16.5
