### ISSUE TITLE
[1.20.1] Weapon Leveling Crash on Start-Up

### ISSUE THREAD

**Issue by Talan67** [Teneted/Tenet#2981] opened 2024-03-01 22:13 UTC
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-554

**Operating System :** Windows 10

**Concerned mod / plugin** : https://www.curseforge.com/minecraft/mc-mods/weapon-leveling

**Logs :** https://gist.github.com/Talan67/9e27c71487e63c11d1758ec0c3d81287 https://gist.github.com/Talan67/eea23af5a13fc265add42391aa9076c8

**Steps to Reproduce :**
 1. Install Weapon Leveling and Architectury API
 2. Startt Server
 3. Crash

**Description of issue :** N/A

**Comment by killer2gudpl** [comment] 2024-03-03 15:44
Duplicate of my issue #2931

**Closed as completed** 2024-03-04 04:17 UTC
