### ISSUE TITLE
[1.16.5] Cannot load server

### ISSUE THREAD

**Issue by Sam-Chai** [Teneted/Tenet#1430] opened 2021-06-11 07:14 UTC
**Minecraft Version :** 1.16.5

**Mohist Version :** #360

**Operating System :** Windows 10

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** just alex's mobs

**Plugin list :** nope

**Description of issue :** 
Cannot load Server data pack when start mohist.
```
Found validation problem in {alexsmobs:gameplay/seal_reward}.pools[0].entries[1].functions[0]: Parameters [<parameter minecraft:origin>] are not provided in this context
[15:11:08 WARN]: 无法加载数据包并启动服务器，尝试修复数据包或使用“--safeMode”参数重置数据包为原版
```
Only have alex's mobs mod. And I turn on "--safeMode" on start script also cannot start server.

**Comment by Sam-Chai** [comment] 2021-06-11 07:21
latest build cannot load either.

**Comment by Dokman** [comment] 2021-06-14 16:39
you have installed Citadel library mod?
PS: In my end is working well.

**Comment by Sam-Chai** [comment] 2021-06-25 13:35
> you have installed Citadel library mod?
> 
> PS: In my end is working well.


Yeah. I installed Citadel

**Comment by Dokman** [comment] 2021-06-26 15:56
I cannot reproduce it

**Comment by joaoespanhol** [comment] 2021-08-06 10:34
has been fixed with last update
@Romaindu35

**Closed as completed** 2021-08-06 11:15 UTC
Labels: 1.16.5, More Info Needed, Cannot Reproduce, Wait
