### ISSUE TITLE
Internal Exception Error

### ISSUE THREAD

**Issue by grimreeaperr** [Teneted/Tenet#2028] opened 2022-01-31 09:42 UTC
**Minecraft Version :** {1.16.5}

**Mohist Version :** {MD5: c5f7e0f3a3d5c3e924cc231b28951d38}
![Screenshot (403)](https://user-images.githubusercontent.com/78335256/151771120-6b65a935-fc8e-45c6-aa7e-55886b679de3.png)

**Operating System :** {Windows 10}
[latest.log](https://github.com/MohistMC/Mohist/files/7969705/latest.log)

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {Wyrmroost-1.16.3-1.2.11.jar, DoggyTalents-1.16.5-2.1.15.jar, mcw-windows-2.0.2-mc1.16.5.jar, Guide-API-VP-1.16.5-2.2.2.jar, Neat+1.7-27 (1).jar, villagernames_1.16.5-3.4.jar, citadel-1.8.1-1.16.5.jar, alexsmobs-1.12.1.jar, MutantBeasts-1.16.4-1.1.3 (2).jar, sophisticatedbackpacks-1.16.5-3.15.1.503.jar, guardvillagers-1.16.5.1.2.6.jar, mcw-doors-1.0.5-mc1.16.5.jar, MekanismGenerators-1.16.5-10.1.1.456.jar, carryon-1.16.5-1.15.5.22.jar, chat_heads-0.5.1-forge-1.16.5.jar, twilightforest-1.16.5-4.0.870-universal.jar, supplementaries-1.16.5-0.17.12b.jar, corpse-1.16.5-1.0.6.jar, FarmersDelight-1.16.5-0.5.4 (1).jar, AmbientSounds_v3.1.11_mc1.16.5.jar, BiomesOPlenty-1.16.5-13.1.0.485-universal.jar, mcw-trapdoors-1.0.4-mc1.16.5.jar, mcw-fences-1.0.2-mc1.16.5.jar, supermartijn642corelib-1.0.16-mc1.16.5.jar, Botania-1.16.5-420.2.jar, cavesandcliffs-1.16.5-7.2.0.jar, curios-forge-1.16.5-4.0.7.0.jar, eidolon-0.2.7.jar, Patchouli-1.16.4-53.2.jar, collective-1.16.5-3.8.jar, advancednetherite-1.10.0-1.16.5.jar, TheAbyss2+2.2.0-1+1.16.5.jar, cavebiomeapi-1.16.5-1.4.2.jar, MekanismTools-1.16.5-10.1.1.456.jar, SpartanWeaponry-1.16.4-2.1.0-beta-4 (1).jar, mcw-roofs-2.0.1-mc1.16.5-4.jar, architectury-1.28.48.jar, Craftable_NameTag+1.16.x.jar, cloth-config-4.13.49-forge.jar, conjuring-forgery-0.2.2.jar, smallships-1.16.5-1.10.1.jar, voidtotem-1.16.5-1.4.0.jar, mcw-lights-1.0.2-mc1.16.5.jar, mowziesmobs-1.5.19.jar, ogres-0.3.jar, ftb-library-forge-1605.3.4-build.90.jar, ftb-ranks-forge-1605.1.5-build.16.jar, mining_helmet-1.16.5-2.0.1.jar, Bountiful+Baubles+FORGE-1.16.3-0.0.2 (2).jar, additionallanterns-1.0.0-mc1.16.jar, treeharvester_1.16.5-4.1.jar, AoA3-3.5.4-1.16.5.jar, jei-1.16.5-7.7.1.145.jar, callablehorses-1.16.3-1.2.1.4.jar, abnormals_core-1.16.5-3.3.1.jar, goblintraders-1.6.0-1.16.3.jar, Mekanism-1.16.5-10.1.1.456.jar, kobolds-0.1.jar, hammermod-1.16.5 (2).jar, Waystones_1.16.5-7.6.4.jar, Fallingleaves-1.16.5-1.0.1.jar, mcw-paintings-1.0.2-mc1.16.5.jar, RingOfRepair-Forge-1.16.5-1.2.15.jar, journeymap-1.16.5-5.8.0beta11.jar, SimpleStorageNetwork-1.16.5-1.5.1.jar, SereneSeasons-1.16.5-4.0.1.123-universal.jar, configured-1.5.1-1.16.5.jar, netheritehorsearmor-1.7.jar, OuterEnd-0.2.14.jar, decorative_blocks-1.16.4-1.7.2.jar, fantasy-forge-1.1.1 (1).jar, champions-forge-1.16.5-2.0.1.8.jar, [1.16.5]-Epic-Knights-Armor-and-Weapons-5.6v.jar, pedestals-0.8s_hotfix_5.jar, mahoutsukai-1.16.5-v1.34.0.jar, iceandfire-2.1.9-1.16.5.jar, mohist-1.16.5-933-universal.jar, Atum-1.16.5-2.2.9.jar, selene-1.16.5-1.9.0.jar, ironchest-1.16.5-11.2.21.jar, upgrade_aquatic-1.16.5-3.1.2.jar, BrassAmberBattleTowers-1.16.5-1.1.4.jar, voicechat-forge-1.16.5-1.7.8.jar, swingthroughgrass-1.16.4-1.5.3 (1).jar, ToolBelt-1.16.5-1.16.0.jar, silent-lib-1.16.5-4.10.0.jar, baubles-1.8.7.1-1.16.5.jar, pamhc2crops-1.16.3-1.0.2.jar, CreativeCore_v2.2.1_mc1.16.5.jar, trolls-0.2.jar, jeiintegration_1.16.5-7.0.1.15.jar, SpartanShields-1.16.5-2.1.2 (1).jar, pamhc2foodcore-1.16.3-1.0.2.jar, AutoRegLib-1.6-49.jar, AkashicTome-1.4-16.jar, StorageDrawers-1.16.3-8.5.1.jar, sit-1.16.5-v1.3.1.jar, goblins-0.2.jar, twoplayersonehorse-1.16.4-2.0.2.jar, structurize-0.13.252-ALPHA-universal.jar, Elvenation-1.16.5-1.0.3.jar, minecolonies-1.16.5-1.0.309-RELEASE.jar, Vampirism-1.16.5-1.8.6.jar, VampirismIntegrations-1.16.5-1.6.1.jar, VampiresNeedUmbrellas-1.16.5-1.1.5.jar, GodlyVampirism-1.16.5-1.0.2.jar, Werewolves-1.16.5-1.8-0.5.6.jar, enhancedcelestials-2.0.9-1.16.5.jar, Aquaculture-1.16.5-2.1.21.jar, Craftable+Horse+Armour++Saddle-1.16.5-1.7--Forge.jar, TA2+beginning+1.0.9+1.16.5 (1).jar, drinkbeer-1.16.5-2.3.5.jar, xptome-1.16.5-v2.1.2 (1).jar}

**Plugin list :** {No plugins}

**Description of issue :** {I loaded mohist onto my server after seeing that the vampirism glitch was fixed, but as I was loading into my server this error came up. I will link the latest log and the error name.}

**Comment by grimreeaperr** [comment] 2022-01-31 09:53
The version before this worked fine on the server.

**Comment by Mike5357** [comment] 2022-02-08 03:50
Duplicate of #1998

**Closed as completed** 2022-02-08 05:04 UTC
Labels: Duplicate
