### ISSUE TITLE
[1.20.2] World Logging Problem

### ISSUE THREAD

**Issue by MultigamingDE** [Teneted/Tenet#2859] opened 2023-12-29 17:37 UTC
**Minecraft Version :** 1.20.2

**Mohist Version :** 126

**Operating System :** WIN11Business/Debian12

**Concerned mod / plugin** : My-World / (https://www.spigotmc.org/resources/myworlds.39594/download?version=523183)

**Logs :** [18:23:28 WARN]: [My_Worlds]   World aa loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:28 WARN]: [My_Worlds]   Using inventory of world aa
[18:23:28 INFO]: world.getWorldFolder() of aa is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:28 WARN]: [My_Worlds]   World aa loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:36 INFO]: MultigamingDE issued server command: /mw tp world
[18:23:36 INFO]: world.getWorldFolder() of Bauwelt is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:36 WARN]: [My_Worlds]   World Bauwelt loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:36 WARN]: [My_Worlds] Deciding inventory of aa useWorldInv=true
[18:23:36 INFO]: world.getWorldFolder() of aa is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:36 WARN]: [My_Worlds]   World aa loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:36 WARN]: [My_Worlds]   Using inventory of world aa
[18:23:36 INFO]: world.getWorldFolder() of aa is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:36 WARN]: [My_Worlds]   World aa loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:36 INFO]: world.getWorldFolder() of Bauwelt is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:36 WARN]: [My_Worlds]   World Bauwelt loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:36 WARN]: [My_Worlds] Deciding inventory of world useWorldInv=true
[18:23:36 INFO]: world.getWorldFolder() of world is C:\Pixelmon\.\world
[18:23:36 WARN]: [My_Worlds]   World world loaded, using C:\Pixelmon\.\world\playerdata
[18:23:36 WARN]: [My_Worlds]   Using inventory of world Bauwelt
[18:23:36 INFO]: world.getWorldFolder() of Bauwelt is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:36 WARN]: [My_Worlds]   World Bauwelt loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:39 INFO]: MultigamingDE issued server command: /p h 2
[18:23:39 INFO]: world.getWorldFolder() of Bauwelt is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:39 WARN]: [My_Worlds]   World Bauwelt loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:39 WARN]: [My_Worlds] Deciding inventory of world useWorldInv=true
[18:23:39 INFO]: world.getWorldFolder() of world is C:\Pixelmon\.\world
[18:23:39 WARN]: [My_Worlds]   World world loaded, using C:\Pixelmon\.\world\playerdata
[18:23:39 WARN]: [My_Worlds]   Using inventory of world Bauwelt
[18:23:39 INFO]: world.getWorldFolder() of Bauwelt is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:39 WARN]: [My_Worlds]   World Bauwelt loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:39 INFO]: world.getWorldFolder() of Bauwelt is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:39 WARN]: [My_Worlds]   World Bauwelt loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:39 WARN]: [My_Worlds] Deciding inventory of Bauwelt useWorldInv=true
[18:23:39 INFO]: world.getWorldFolder() of Bauwelt is C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt
[18:23:39 WARN]: [My_Worlds]   World Bauwelt loaded, using C:\Pixelmon\.\Bauwelt\dimensions\minecraft\bauwelt\playerdata
[18:23:39 WARN]: [My_Worlds]   Using inventory of world Bauwelt

**Steps to Reproduce :**
 1. Do this Start Server with A oneBlock and Skyblock 
 2. or create some worlds 
 3. test if inventory is separated (sometime yes but most time no)

**Description of issue :** Give all details about your issue
Logging.LOGGER.info("world.getWorldFolder() of " + world.getName() + " is " + world.getWorldFolder().getAbsolutePath());

seems like it is not correctly logging the worlds i enter and leave

**Comment by SimonMage** [comment] 2023-12-29 18:37
Mayb can help you, could you try with this similar plugin?
https://www.spigotmc.org/resources/separe-world-items.74148/
If the issue is the same is mohist problem, if not, the problem is caused by the compatibility from spigot and forge and maybe Mgazul can fix it, but first of all try with the other one

**Comment by MultigamingDE** [comment] 2023-12-29 19:05
i can confirm after i figured out how it works it works i try it a bit more before i set it in production

**Comment by SimonMage** [comment] 2023-12-30 01:18
I think can be marked as solved

**Comment by SimonMage** [comment] 2023-12-30 01:18
@Mgazul

**Closed as completed** 2024-01-04 04:28 UTC
