### ISSUE TITLE
[1.7.10] Incompatibility with MobiusCore

### ISSUE THREAD

**Issue by Maks-Haswell** [Teneted/Tenet#61] opened 2019-12-20 10:31 UTC
Mohist Version: Build 71
MobiusCore Version: 1.2.5
Crash report: https://hastebin.com/xayavihava.rb

Crash during server startup.

**Comment by GedeonGrays** [comment] 2019-12-20 17:59
_Hello o/_

Duplicate of issue #37

_P.S. Of course, I understand that not everyone can wait for an answer from the developers, but then you will duplicate all my closed issues that do not confirm the fix. Thanks._

**Comment by Maks-Haswell** [comment] 2019-12-21 02:14
> _Hello o/_
> 
> Duplicate of issue #37
> 
> _P.S. Of course, I understand that not everyone can wait for an answer from the developers, but then you will duplicate all my closed issues that do not confirm the fix. Thanks._

I encountered a similar problem that you have and decided to copy the message a little if not against

**Comment by GedeonGrays** [comment] 2019-12-21 11:15
> I encountered a similar problem that you have and decided to copy the message a little if not against

Okay, I don't mind. I hope the developers pay attention to the rest of my closed, but not fixed issues.

**Closed as completed** 2020-02-11 05:25 UTC
