### ISSUE TITLE
[BUG 1.16.6] Map generation bug (CHUNK)

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1539] opened 2021-07-10 22:12 UTC
Minecraft Version: 1.16.5
Build: tested all builds#650-#701
Logs: NONE
Mods: screen
Plugins: screen
BUG: SEE SCREEN!

Please, please! Finally fix the bugs of custom generation! My world generation costs new biomes from Abnormals, my friends have BiomesOplenty, we have very big bugs of map generation, it is after the server reboot that it is not a single one, we use the latest versions of the kernel and used different ones and tested, Your kernel breaks chunks of custom generation! Please, I beg you, fix this case! It's impossible to play! All chunks are broken - the map is terrible, vanilla chunks - good ones do not break, any mod that adds custom generation - chunks break!
![image](https://user-images.githubusercontent.com/86250668/125177489-d0fd8200-e1e4-11eb-9b43-34ecb4f592f2.png)
![image](https://user-images.githubusercontent.com/86250668/125177490-d35fdc00-e1e4-11eb-9383-b7f96c1bc41b.png)
![image](https://user-images.githubusercontent.com/86250668/125177492-dd81da80-e1e4-11eb-80bb-856785567620.png)
![image](https://user-images.githubusercontent.com/86250668/125177495-ec688d00-e1e4-11eb-89d7-7437d30a3946.png)
![image](https://user-images.githubusercontent.com/86250668/125177496-f25e6e00-e1e4-11eb-9541-4d2fe95e1bb3.png)
![image](https://user-images.githubusercontent.com/86250668/125177498-f5595e80-e1e4-11eb-9ac0-fbc5a562648a.png)
![image](https://user-images.githubusercontent.com/86250668/125177502-f8544f00-e1e4-11eb-96af-7b783b96bb34.png)

When I used a clean forge or a single world, there were no problems! This problem is observed only on Mohist! And not just me!

**Comment by Shawiizz** [comment] 2021-07-10 22:14
Duplicate of #1511

**Closed as completed by Shawiizz** 2021-07-10 22:15 UTC
