### ISSUE TITLE
[1.16.5] Badly compressed packet

### ISSUE THREAD

**Issue by Sosea1** [Teneted/Tenet#2043] opened 2022-02-07 16:05 UTC
**Minecraft Version :** 1.16.5

**Mohist Version :** 936

**Operating System :** win 11

**Concerned mod / plugin** : without plugins, i had many mods

**Logs :** https://gist.github.com/Sosea1/8189edfb9a09e1b2ce8ef9ff90abe43c

**Steps to Reproduce :**
 1. Install all mods
 2. Try to connect to server
 3. Then my friend gets the issue: Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2227612 is larger than maximum of 2097152

**Description of issue :** just on a forge server its all working, but with mohist server im getting this issue. Without mods mohist server is working good. I have about 90 mods on my server, maybe one mod is causing the issue.

P.S. sory for bad english)

**Comment by Mike5357** [comment] 2022-02-08 00:26
Duplicate of #2010, #1998

**Closed as completed** 2022-02-08 04:18 UTC
Labels: Duplicate
