### ISSUE TITLE
启动失败(1.12.2 Build#208)

### ISSUE THREAD

**Issue by colinxu2020** [Teneted/Tenet#1301] opened 2021-05-03 10:14 UTC
版本:MC1.12.2 Build#208
日志:
正在检测库文件是否完整...
全局进度 >> 11%
正在下载文件: scala-continuations-library_2.11-1.0.2.jar 大小: 24.770508 KB
文件 scala-continuations-library_2.11-1.0.2.jar 下载已完成
支持库文件检测完毕,所有文件都已存在.
检查更新中......
如果您不想启用更新检查，请在mohist.yml 中将check_update项设置为false
未找到更新，最新版本: (1.9-1.12.2-208) 当前版本: (1.9-1.12.2-208)
搜索不兼容的插件...
搜索不兼容的mod...
Mohist启动中…
正在加载支持库文件，请等待...
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.mohistmc.MohistMC.main(MohistMC.java:60)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, C:\Users\许 家澍\AppData\Local\Temp\jansi-64-8791401098761795758.dll: Can't find dependent libraries]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        at org.fusesource.jansi.internal.Kernel32.<clinit>(Kernel32.java:37)
        at org.fusesource.jansi.WindowsAnsiOutputStream.<clinit>(WindowsAnsiOutputStream.java:52)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStream(ConsoleAppender.java:263)
        at org.apache.logging.log4j.core.appender.ConsoleAppender.getDefaultManager(ConsoleAppender.java:226)
        at org.apache.logging.log4j.core.appender.ConsoleAppender.createDefaultAppenderForLayout(ConsoleAppender.java:172)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:581)
        at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
        at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:86)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:74)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:227)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:618)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:58)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37)
        ... 5 more
{Answer here}

**Comment by Shawiizz** [comment] 2021-05-07 08:32
Since we can't reproduce this, I close this for now. Please keep Mohist updated to latest version asap :)

**Closed as completed by Shawiizz** 2021-05-07 08:32 UTC
Labels: Question, More Info Needed, Cannot Reproduce
