### ISSUE TITLE
World not saving on close - 1.12.2

### ISSUE THREAD

**Issue by VOrlando520** [Teneted/Tenet#939] opened 2021-02-14 14:15 UTC
Using latest mohist for 1.12.2 and the world is not saving on close. Every reboot the server will roll back to the last manual save point done for the server.

**Comment by Shawiizz** [comment] 2021-02-14 14:17
I don't have this issue. This is caused by a mod or a plugin. Please remove them 1 per 1 to see which is causing that bug.

**Comment by VOrlando520** [comment] 2021-02-14 14:18
That's already been done, hence why I'm posting here. A couple fellow server owners are having the same issue as I as well.

**Comment by Shawiizz** [comment] 2021-02-14 14:36
I just tested and i can't reproduce your issue.

**Comment by VOrlando520** [comment] 2021-02-14 15:27
and you are on the latest mohist?

**Comment by Shawiizz** [comment] 2021-02-14 15:28
Yes

**Comment by VOrlando520** [comment] 2021-02-14 22:47
Alright after some testing today, it seems only chests are getting wiped and I've removed every plugin I can think of that would interact with chests and still can not figure out the issue.

**Comment by SekiAlpha** [comment] 2021-02-14 23:14
I can confirm I'm getting this issue as well.

**Comment by Rabbit0w0** [comment] 2021-02-15 12:53
You may save the data manually while we are checking this error

**Comment by Shawiizz** [comment] 2021-02-15 13:02
I can't reproduce your issue. I tested to put things in a chest, i restarted my server and everything is fine.

**Comment by hoctz** [comment] 2021-02-15 13:38
I'm having the same issue here

**Comment by Shawiizz** [comment] 2021-02-15 13:40
I tested 3 times on 3 differents machine and i still can't reproduce this issue.

**Comment by Shawiizz** [comment] 2021-02-15 14:53
Try with a fresh install and **without any plugins & mods**, you'll see that it saves chest content correctly.

**Comment by laboriens** [comment] 2021-02-15 15:56
give your list of plugins and mods maybe you have one that also registers

**Comment by Shawiizz** [comment] 2021-02-16 09:12
Try again to find which mod / plugin is causing that by removing them 1 per 1. I still can't reproduce this without any mod and plugin.

**Comment by VOrlando520** [comment] 2021-02-16 23:49
Turns out it isnt world saving, but it seems to be a chest issue. It's not saving chest inventories and thats with just mohist and nothing else on the server

**Comment by Shawiizz** [comment] 2021-02-16 23:51
Like I said, try with a clean install without any plugins and mods and you'll see that everything is fine.

**Comment by VOrlando520** [comment] 2021-02-17 00:26
I just literally said that twice, i did that with a clean install. chests are not saving on any version above 159.

**Comment by joaoespanhol** [comment] 2021-02-17 00:35
I don't have that problem.
I'm using the latest version.
My server resumes every 3 hours, and it has not been a problem so far.
I didn't even have complaints from the players.
I am use last version mohist. (11.12.2-192)

**Comment by SekiAlpha** [comment] 2021-02-17 01:38
It's probably a mod issue but this doesn't occur with just forge. Figuring out what mod does this will be difficult.

**Comment by Shawiizz** [comment] 2021-03-01 15:53
I close this since it's not reproduceable with a clean install. If needed, you can recreate the issue.

**Closed as completed by Shawiizz** 2021-03-01 15:53 UTC
Labels: Question
